# Auto-generates bug reports from test results

import os

def generate_bug_report(test_name, status, screenshot_path, timestamp):
    # Create reports folder if it doesn't exist
    os.makedirs("reports", exist_ok=True)

    # Build the report content
    report = f"""==========================
BUG REPORT
==================================
Test Name  : {test_name}
Status     : {status}
Timestamp  : {timestamp}
Screenshot : {screenshot_path}
==================================
Notes: Auto-generated by QA automation suite
==================================
"""
    
    # Save to file
    file_path = f"reports/{test_name}_bug_report.txt"
    with open(file_path, "w") as f:
        f.write(report)

    print(f"Bug report saved: {file_path}")
    return file_path
