# Day 30 - AI Generated Test Suite for Posts API
# Generated from prompt by Komal

import pytest
import os
from datetime import datetime 
from playwright.sync_api import sync_playwright

BASE_URL = "https://jsonplaceholder.typicode.com"
REPORT_FILE = "reports/posts_api_report.txt"

# ===== FIXTURE =====
@pytest.fixture()
def api_request():
    with sync_playwright() as p:
        request_context = p.request.new_context(base_url=BASE_URL)
        yield request_context
        request_context.dispose()

# ===== REPORT HELPER =====
def save_result(test_name, status, details):
    os.makedirs("reports", exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(REPORT_FILE,"a") as f:
        f.write(f"[{timestamp}] {test_name} | {status} | {details}\n")

# ===== TESTS =====
def test_get_single_post(api_request):
    response = api_request.get("/posts/1")

    assert response.status == 200, f"Expected 200, got {response.status}"

    data = response.json()
    assert data["id"] == 1
    assert data["userId"] == 1
    assert "title" in data
    assert "body" in data

    print(f"✅ GET Post | id:{data['id']} | title: {data['title'][:30]}...")
    save_result("test_get_single_post", "PASSED", f"id={data['id']}, title={data['title'][:30]}")

def test_create_post(api_request):
    new_post = {
        "title": "AI QA Engineer Test",
        "body": "Generated by Komal's AI QA automation suite",
        "userId": 1
    }

    response = api_request.post("/posts", data=new_post)

    assert response.status == 201, f"Expected 201, got {response.status}"

    data = response.json()
    assert data["title"] == "AI QA Engineer Test"
    assert data["userId"] == 1
    assert "id" in data

    print(f"✅ CREATE Post | new id:{data['id']} | title: {data['title']}")
    save_result("test_create_post", "PASSED", f"created id={data['id']}, title={data['title']}")

def test_update_post(api_request):
    updated_post = {
        "id": 1,
        "title": "Updated by AI QA Suite",
        "body": "This post was updated by Komal's automation",
        "userId": 1
    }

    response = api_request.put("/posts/1", data=updated_post)

    assert response.status == 200, f"Expected 200, got {response.status}"

    data = response.json()
    assert data["title"] == "Updated by AI QA Suite"
    assert data["id"] == 1

    print(f"✅ UPDATE Post | id:{data['id']} | new title: {data['title']}")
    save_result("test_update_post", "PASSED", f"updated id={data['id']}, title={data['title']}")

def test_delete_post(api_request):
    response = api_request.delete("/posts/1")

    assert response.status == 200, f"Expected 200, got {response.status}"

    print("✅ DELETE Post | post/1 deleted successfully")
    save_result("test_delete_post", "PASSED", "post/1 deleted successfully")

def test_get_invalid_post(api_request):
    response = api_request.get("/posts/99999")

    assert response.status == 404, f"Expected 404, got {response.status}"

    print("✅ GET Invalid Post | correctly returned 404")
    save_result("test_get_invalid_post", "PASSED", "404 returned for invalid post")